CREATE TABLE employees (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name   VARCHAR(150)  NOT NULL,
                           email       VARCHAR(255)  NOT NULL,
                           job_title   VARCHAR(100)  NOT NULL,
                           department  VARCHAR(100)  NOT NULL,
                           country     VARCHAR(100)  NOT NULL,
                           salary      NUMERIC(15,2) NOT NULL,
                           hire_date   DATE          NOT NULL,
                           status      VARCHAR(20)   NOT NULL,
                           created_at  TIMESTAMP     NOT NULL,
                           updated_at  TIMESTAMP     NOT NULL,
                           CONSTRAINT uk_employees_email UNIQUE (email),
                           CONSTRAINT ck_employees_salary_positive CHECK (salary > 0)
);